name: Regenerate Paws

on:
  schedule:
    # At 12:00, on day 1 of the month, every 4 months
    - cron: "0 12 1 */4 *"
  workflow_dispatch:
    inputs:
    text_to_print:
      description: "Manual re-build"

jobs:
  update-deps:
    runs-on: ubuntu-latest
    name: update-deps

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: "2.17.1"

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libgit2-dev
          sudo apt-get install -y libharfbuzz-dev libfribidi-dev

      - name: Install Paws Dependencies
        run: |
          install.packages('remotes')
          remotes::install_deps('paws.common', dependencies = TRUE)
          remotes::install_deps('make.paws', dependencies = TRUE)
        shell: Rscript {0}

      - name: Install Paws Packages
        run: |
          remotes::install_local('paws.common', force = TRUE)
          remotes::install_local('make.paws', force = TRUE)
        shell: Rscript {0}

      - name: Create Branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b regen_paws

      - name: Update dependencies
        run: |
          make deps
          make update-deps

      - name: List Apis
        run: |
          make.paws::github_api_list()
        shell: Rscript {0}

      - uses: actions/upload-artifact@v3
        with:
          name: api_list
          path: |
            apis/

      - name: clear down
        run: |
          rm -rf cran
          rm -rf paws
          rm -rf apis

      - name: Create Commit Message
        run: |
          git add .
          git commit -m "update dependencies"
          git push origin regen_paws

  build-apis-1:
    needs: update-deps

    runs-on: ubuntu-latest
    name: build-apis-1

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: "2.17.1"

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libgit2-dev
          sudo apt-get install -y libharfbuzz-dev libfribidi-dev

      - name: Install Paws Dependencies
        run: |
          install.packages('remotes')
          remotes::install_deps('paws.common', dependencies = TRUE)
          remotes::install_deps('make.paws', dependencies = TRUE)
        shell: Rscript {0}

      - name: Install Paws Packages
        run: |
          remotes::install_local('paws.common', force = TRUE)
          remotes::install_local('make.paws', force = TRUE)
        shell: Rscript {0}

      - name: Change Branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch origin
          git switch regen_paws
          git pull

      - name: Get dependencies
        run: |
          make deps

      - uses: actions/download-artifact@v3
        with:
          name: api_list
          path: apis

      - name: Build Apis
        run: |
          apis <- readLines("./apis/api_chunk_1.txt")
          make.paws::github_build_apis(apis = apis)
        shell: Rscript {0}

      - uses: actions/upload-artifact@v3
        with:
          name: build_1
          path: |
            cran/
            paws/

  build-apis-2:
    needs: update-deps

    runs-on: ubuntu-latest
    name: build-apis-2

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: "2.17.1"

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libgit2-dev
          sudo apt-get install -y libharfbuzz-dev libfribidi-dev

      - name: Install Paws Dependencies
        run: |
          install.packages('remotes')
          remotes::install_deps('paws.common', dependencies = TRUE)
          remotes::install_deps('make.paws', dependencies = TRUE)
        shell: Rscript {0}

      - name: Install Paws Packages
        run: |
          remotes::install_local('paws.common', force = TRUE)
          remotes::install_local('make.paws', force = TRUE)
        shell: Rscript {0}

      - name: Change Branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch origin
          git switch regen_paws
          git pull

      - name: Get dependencies
        run: |
          make deps

      - uses: actions/download-artifact@v3
        with:
          name: api_list
          path: apis

      - name: Build Apis
        run: |
          apis <- readLines("./apis/api_chunk_2.txt")
          make.paws::github_build_apis(apis = apis)
        shell: Rscript {0}

      - uses: actions/upload-artifact@v3
        with:
          name: build_2
          path: |
            cran/
            paws/

  build-apis-3:
    needs: update-deps

    runs-on: ubuntu-latest
    name: build-apis-3

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: "2.17.1"

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libgit2-dev
          sudo apt-get install -y libharfbuzz-dev libfribidi-dev

      - name: Install Paws Dependencies
        run: |
          install.packages('remotes')
          remotes::install_deps('paws.common', dependencies = TRUE)
          remotes::install_deps('make.paws', dependencies = TRUE)
        shell: Rscript {0}

      - name: Install Paws Packages
        run: |
          remotes::install_local('paws.common', force = TRUE)
          remotes::install_local('make.paws', force = TRUE)
        shell: Rscript {0}

      - name: Change Branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch origin
          git switch regen_paws
          git pull

      - name: Get dependencies
        run: |
          make deps

      - uses: actions/download-artifact@v3
        with:
          name: api_list
          path: apis

      - name: Build Apis
        run: |
          apis <- readLines("./apis/api_chunk_3.txt")
          make.paws::github_build_apis(apis = apis)
        shell: Rscript {0}

      - uses: actions/upload-artifact@v3
        with:
          name: build_3
          path: |
            cran/
            paws/

  merge:
    needs: [build-apis-1, build-apis-2, build-apis-3]

    runs-on: ubuntu-latest
    name: merge-builds

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: "2.17.1"

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libgit2-dev
          sudo apt-get install -y libharfbuzz-dev libfribidi-dev

      - name: Install Paws Dependencies
        run: |
          install.packages('remotes')
          remotes::install_deps('paws.common', dependencies = TRUE)
          remotes::install_deps('make.paws', dependencies = TRUE)
        shell: Rscript {0}

      - name: Install Paws Packages
        run: |
          remotes::install_local('paws.common', force = TRUE)
          remotes::install_local('make.paws', force = TRUE)
        shell: Rscript {0}

      - name: Change Branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch origin
          git switch regen_paws
          git pull

      - uses: actions/download-artifact@v3
        with:
          name: build_1
          path: temp1

      - uses: actions/download-artifact@v3
        with:
          name: build_2
          path: temp2

      - uses: actions/download-artifact@v3
        with:
          name: build_3
          path: temp3

      - name: merge builds
        run: |
          src_paws <- fs::path(c("temp1", "temp2", "temp3"), "paws")
          src_cran <- fs::path(c("temp1", "temp2", "temp3"), "paws")
          for(src in src_paws){fs::dir_copy(src, "paws", overwrite = T)}
          for(src in src_cran){fs::dir_copy(src, "cran", overwrite = T)}
        shell: Rscript {0}

      - name: clear down
        run: |
          rm -rf temp1 temp2 temp3

      - name: Git Commit
        run: |
          git add .
          git commit -m "Build Cran and Paws directories"
          git push origin regen_paws

  collect:
    needs: [merge]

    runs-on: ubuntu-latest
    name: collect

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: "2.17.1"

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libgit2-dev
          sudo apt-get install -y libharfbuzz-dev libfribidi-dev

      - name: Install Paws Dependencies
        run: |
          install.packages('remotes')
          remotes::install_deps('paws.common', dependencies = TRUE)
          remotes::install_deps('make.paws', dependencies = TRUE)
        shell: Rscript {0}

      - name: Install Paws Packages
        run: |
          remotes::install_local('paws.common', force = TRUE)
          remotes::install_local('make.paws', force = TRUE)
        shell: Rscript {0}

      - name: Change Branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch origin
          git switch regen_paws
          git pull

      - name: Get dependencies
        run: |
          make deps

      - uses: actions/download-artifact@v3
        with:
          name: build_1
          path: temp1

      - uses: actions/download-artifact@v3
        with:
          name: build_2
          path: temp2

      - uses: actions/download-artifact@v3
        with:
          name: build_3
          path: temp3

      - name: Build Apis
        run: |
          apis <- fs::path(c("temp1", "temp2", "temp3"), "api_names.RDS")
          make.paws::github_make_category_collection(api_names = apis)
          make.paws::github_make_collection(api_names = apis)
        shell: Rscript {0}

      - name: Git Commit
        run: |
          git add .
          git commit -m "Make category collections"
          git push origin regen_paws

      - name: Create Github Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --title "Regenerate Paws" --body "Regenerate Paws SDK"
