name: Regenerate Paws

# on:
#   schedule:
#     # At 12:00, on day 1 of the month, every 4 months
#     - cron:  '0 12 1 */4 *'

on: workflow_dispatch

jobs:
  regen:
    runs-on: ubuntu-latest
    name: regen-paws

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '2.17.1'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libgit2-dev
          sudo apt-get install -y libharfbuzz-dev libfribidi-dev
          sudo apt install -y gh

      - name: Install dependencies
        run: |
          install.packages('remotes')
          remotes::install_deps('paws.common', dependencies = TRUE)
          remotes::install_deps('make.paws', dependencies = TRUE)
          remotes::install_cran("rcmdcheck")
        shell: Rscript {0}

      - name: Install paws packages
        run: |
          remotes::install_local('paws.common', force = TRUE)
          remotes::install_local('make.paws', force = TRUE)
        shell: Rscript {0}

      - name: create branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b regen_paws

      - name: Regenerate Paws
        run: |
          make update-deps
          make build

      - name: Commit message
        run: |
          git add .
          git commit -m "Regenerate Paws"
          git push origin regen_paws

      - uses: Create Github Pr
        run: |
          gh auth login --with-token ${{ secrets.GITHUB_TOKEN }}
          gh pr create --title "Regenerate Paws: $(date +'%Y-%m-%d')" --body "Regenerate Paws SDK"
