name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Unit-Tests:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: 'ubuntu-18.04', R: '4.0' }

    steps:
      - uses: actions/checkout@v2

      - name: Install R
        uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.R }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install paws packages
        run: |
          install.packages('remotes')
          remotes::install_local('paws.common', dependencies = T)
          remotes::install_local('make.paws', dependencies = T)
          remotes::install_local('cran/paws', dependencies = T)
        shell: Rscript {0}

      - name: Run checks
        run: |
          R CMD build paws.common && R CMD check --as-cran --run-donttest --no-manual paws.common_*.tar.gz
          R CMD build make.paws && R CMD check --as-cran --run-donttest --no-manual make.paws_*.tar.gz
          R CMD build cran/paws && R CMD check --as-cran --run-donttest --no-manual paws_*.tar.gz

      - name: Install covr
        run: |
          install.packages('covr')
        shell: Rscript {0}

      - name: Get code coverage
        run: |
          Rscript script/codecov.R paws.common make.paws
